name: tabbik

packages:
  - packages/*
  - packages/*/*

dependencies:
  flutter:
    sdk: flutter

  injectable: ^2.3.2
  get_it: ^7.6.4
  intl: any
  go_router: ^12.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1

  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  gap: ^3.0.1
  cupertino_modal_sheet: ^1.1.0
  clipboard: ^0.1.3
  url_launcher: ^6.2.4
  image_picker: ^1.0.7

  flutter_screenutil: ^5.9.0
  decimal: ^2.3.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  flutter_lints: ^3.0.0


scripts:
  generate:flutter:all:
    run: melos exec -c 10 --depends-on="build_runner" --ignore="app" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  generate:flutter:clean:
    run: melos exec -c 10 --depends-on="build_runner" --flutter -- "flutter pub run build_runner clean"
    description: Build all generated files for Flutter packages in this project.
  generate:flutter:app:
    run: melos exec -c 1 --depends-on="build_runner" --scope="app" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.

  build:apk:dev_test:
    run: melos exec -c 1 --scope="app" --flutter -- "flutter build apk --split-per-abi --flavor dev_test -t lib/main_dev_test.dart --no-tree-shake-icons"

  build:ipa:staging_test:
    run: melos exec -c 1 --scope="app" --flutter -- "flutter build ipa --flavor staging_test -t lib/main_staging_test.dart --no-tree-shake-icons"

  localization_keys_gen:
    run: melos exec -c 5 "dart run ../../localization_generate/generate.dart -S assets/localization -f keys -O lib/logic/localization -o locale_keys.g.dart"
    description: Generate localization keys
