name: auth
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  core:
    path: ../core

  # components:
  #   path: ../components

  # theme:
  #   path: ../theme

  injectable: ^2.3.2
  flutter_bloc: ^8.1.5
  go_router: ^12.0.3
  get_it: ^7.6.7
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.2
  freezed_annotation: ^2.4.1

  local_auth: ^2.2.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  injectable_generator: ^2.5.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/
    - assets/images/
    # - assets/svgs/
    # - assets/fonts/
