name: app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  core:
    path: ../core

  theme:
    path: ../theme
  
  auth: 
    path: ../auth

  components:
    path: ../components
  
  club: 
    path: ../club

  flutter_bloc: ^8.1.3

  cupertino_icons: ^1.0.2
  go_router: ^12.0.3
  injectable: ^2.3.2
  get_it: ^7.6.4

  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  flutter_flavorizr: ^2.2.1

flutter:
  uses-material-design: true


flavorizr:
  flavors:
    prod:
      app:
        name: "Tabbik"
      android:
        applicationId: "kg.tabbik.prod"

      ios:
        bundleId: "kg.tabbik.prod"

    dev:
      app:
        name: "Tabbik Dev"

      android:
        applicationId: "kg.tabbik.dev"
      ios:
        bundleId: "kg.tabbik.dev"
