name: core
description: "A new Flutter module project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  theme:
    path: ../theme

  components:
    path: ../components

  injectable: ^2.3.2
  get_it: ^7.6.4
  intl: ^0.18.1
  go_router: ^12.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  permission_handler: ^11.3.0
  equatable: ^2.0.5
  cached_network_image: ^3.3.1

  hive: ^2.2.3
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  gap: ^3.0.1
  cupertino_modal_sheet: ^1.1.0
  clipboard: ^0.1.3
  url_launcher: ^6.2.4
  image_picker: ^1.0.7

  flutter_screenutil: ^5.9.0
  decimal: ^2.3.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.0
  injectable_generator: ^2.4.1
  freezed: ^2.4.5
  flutter_lints: ^3.0.0


flutter:

