name: club
description: "A new Flutter module project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core

  theme: 
    path: ../theme
  
  components: 
    path: ../components
  
  cupertino_icons: ^1.0.6

  injectable: ^2.3.2
  flutter_bloc: ^8.1.5
  go_router: ^12.0.3
  get_it: ^7.6.7
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  dio: ^5.4.2
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.5.1
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
